### ISSUE TITLE
Invalid zip format on OpT5

### ISSUE THREAD

**Issue by vishnuraju** [paranoidninja/Shuriken#1]
Hi Man,
Thanks a lot for the awesome work. While trying to flash the image on my OpT5 TWRP was throwing up an Invalid Zip Format error. Oxygen OS BETA_24.

**Comment by paranoidninja** [comment]
Can you post a screenshot of the same? Log file for TWRP installation would be more helpful!

**Comment by paranoidninja** [comment]
Closing as resolved over DM :)
